### ISSUE TITLE
Doubts

### ISSUE THREAD

**Issue by ashincoder** [elianiva/elianiva.my.id#15]
@elianiva I have some doubts regarding Lush.nvim. I don't know how to get it to work. Could you please help me. :pleading_face:

**Comment by elianiva** [comment]
you should probably ask this on their repo https://github.com/rktjmp/lush.nvim because they *obviously* know better than me :p

**Comment by ashincoder** [comment]
I know but it would be better to hear from you since you passed through it. Could you just tell the step you've gone through. :pleading_face:
